app/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^admin/', include(admin.site.urls)),
	url(r'^', include('gotem.urls')),
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^app/', include('app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
)

gotem/gotem/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gotem.views.home', name='home'),
    # url(r'^gotem/', include('gotem.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

gotem/urls.py
from django.conf.urls import patterns, url

from gotem import views

urlpatterns = patterns('',
	url(r'^$', views.index),
	url(r'^objective/new/$', views.objective_new),
    url(r'^sprint/(?P<sprint_id>\d+)/$', views.show_sprint, name='show_sprint')
)

gotem/models.py
from django.db import models
from django.forms import ModelForm
from django import forms

class Sprint(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()

    def __unicode__(self):
        return self.name

class Objective(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    sprint = models.ForeignKey(Sprint)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class ObjectiveForm(ModelForm):
    sprint = forms.ModelChoiceField(queryset=Sprint.objects.all(), widget=forms.HiddenInput())

    class Meta:
        model = Objective

gotem/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import simplejson as json
from django.http import Http404, HttpResponseBadRequest
from models import Objective, Sprint, ObjectiveForm

def index(request):
    
    sprint = Sprint.objects.latest('id')
    return show_sprint(request, sprint.id)

def show_sprint(request, sprint_id):
    
    sprint = get_object_or_404(Sprint, id=sprint_id)
    objectives = Objective.objects.filter(sprint=sprint).order_by('-date')
    form = ObjectiveForm(initial = { 'sprint' : sprint })
    model = { 'sprint' : sprint, 'form' : form, 'objectives' : objectives }
    return render(request, 'gotem/index.html', model)

def objective_new(request):
    
    if request.is_ajax():
        objective_form = ObjectiveForm(request.POST or None)
        if objective_form.is_valid():
            new_objective = objective_form.save()
            return render(request, 'gotem/sprint-area/objective-item.html', { 'objective' : new_objective })
        else:
            return HttpResponseBadRequest(json.dumps(objective_form.errors), mimetype="application/json")
    else:
        raise Http404

gotem/templates/gotem/head.html
{% load compress %}
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Gotem</title>
    <meta name="description" content="">
    
    <!-- UNCOMMENT FOR A RESPONSIVE DESIGN
    <meta name="viewport" content="width=device-width, initial-scale=1">
    -->

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    {% compress css %}
        <link type="text/x-scss" rel="stylesheet" href="{% static "scss/screen.scss" %}">
    {% endcompress %}
    
    <!-- <script src="js/vendor/modernizr-2.6.2.min.js"></script> -->

    <!-- Google Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Asap:400,700|Rosario:400,700' rel='stylesheet' type='text/css'>
    
</head>

gotem/templates/gotem/index.html
{% load compress %}
{% load staticfiles%}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

{% include 'gotem/head.html' %}

<body>

<section class="sprints-area">{% include 'gotem/sprints-area.html' %}</section>
<section class="sprint-area">{% include 'gotem/sprint-area.html' %}</section>
<section class="users-area">{% include 'gotem/users-area.html' %}</section>

{% compress js %}
    <script src="{% static 'js/vendor/jquery-1.8.2.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/plugins.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/main.coffee' %}" type="text/coffeescript"></script>
{% endcompress %}

</body>
</html>

gotem/templates/gotem/sprint-area.html
{% include 'gotem/sprint-area/sprint-details.html' %}

<div class="objective-list__controls">
    <div class="objective-add">        
        {% include 'gotem/sprint-area/objective-form.html' %}
    </div>
</div>

{% include 'gotem/sprint-area/objective-list.html' %}

gotem/templates/gotem/sprint-area/objective-form.html
<form action="/objective/new/" method="post" id="objective-form">
    {% csrf_token %}
    <label for="id_title">Name:</label>
    {{ form.name }}
    <label for="id_description">Description:</label>
    {{ form.description }}
    {{ form.sprint }}
    <input type="submit" value="Submit"/>
</form>

gotem/templates/gotem/sprint-area/objective-item.html
<li class="objective-item">
    <div class="objective__header">
        <div class="objective__status"><input type="checkbox"></div>
        <h2 class="objective__title">{{ objective.name }}</h2>
        <div class="objective__controls">
            <div class="objective__comments-count">Comentarios</div>
            <div class="objective__expand">+</div>
        </div>
    </div>
    <div class="objective__details">
        <div class="objective__description"><p>{{ objective.description }}</p></div>
        <div class="objective__comments f-delta">bloque comentarios</div>
    </div>
</li>

gotem/templates/gotem/sprint-area/objective-list.html
<ul class="objective-list nav--stacked" id="objective-list">
    {% for objective in objectives %}
        {% include 'gotem/sprint-area/objective-item.html' %}
    {% endfor %}
</ul>

gotem/templates/gotem/sprint-area/sprint-details.html
<header class="active-sprint" id="active-sprint">
    <h1 class="active-sprint__title">#1 {{ sprint.start_date }} {{ sprint.name }}</h1>
    <p class="active-sprint__done">12/15</p>
    <a class="active-sprint__add" href="">abrir</a>
</header>

gotem/templates/gotem/sprints-area.html
{% load gotem_tags %}

<div class="brand">
	<img src="" alt="">
</div>
<h2>sprint</h2>

{% show_sprints sprint %}

gotem/templates/gotem/sprints-area/sprint-item.html
{% url 'show_sprint' sprint.id as sprint_url %}
{% if sprint != selected_sprint %}
<a href="{{ sprint_url }}" onclick="return load_sprint({{ sprint.id }});">
{% endif %}
    <div class="sprint-item">
        <p class="sprint__number">1</p>
        <hgroup class="sprint__title">
            <h3>{{ sprint.start_date }}</h3>
            <h4>{{ sprint.name }}</h4>
        </hgroup>
        <p class="sprint__done">12/15</p>
    </div>
{% if sprint != selected_sprint %}
</a>
{% endif %}

gotem/templates/gotem/sprints-area/sprint-list.html
<div class="sprints-list nav--stacked" id="sprint-list">
    {% for sprint in sprints %}
        {% include 'gotem/sprints-area/sprint-item.html' %}
    {% endfor %}
</div>

gotem/templates/gotem/users-area.html
{% load staticfiles%}

<div class="brand"><img src="{% static 'img/logo_proxies.png' %}" alt="Proxies"/></div>
<ul class="users-list nav--stacked">
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
    {% include 'gotem/users-area/user-item.html' %}
</ul>

gotem/templates/gotem/users-area/user-item.html
{% load staticfiles%}

<li class="user-item">
    <img src="{% static 'img/img_profile_default.png' %}" alt="Proxi">
    <h2 class="f-gamma">Proxi</h2>
</li>
</li>